### ISSUE TITLE
css styles staring with '-' (-webkit-background-clip: text) should keep capitalization on first character

### ISSUE THREAD

**Issue by cpakken** [Lakkanna/css-converter#23]
Right now
`-webkit-background-clip: text;` converts to   ` webkitBackgroundClip: 'text',`

correct conversion should be `WebkitBackgroundClip: 'text',`

css-in-js libraries will convert the capital 'W' back to '-w'

**Comment by Lakkanna** [comment]
Hi @cpakken,
I'm sorry for the delayed response on this issue. The issue has been fixed in version 0.2.0 now.

`-webkit-background-clip: text;` converts to  `WebkitBackgroundClip: 'text',`

**Comment by Lakkanna** [comment]
Hi @cpakken,

I'm glad to inform you that the issue you reported has been fixed in the latest version. We've closed this issue for now, but if you find that the issue still persists in the latest version, please feel free to reopen this issue and provide us with more details.

Thank you for bringing this issue to our attention and helping us to improve extension.
